In [1]:
import numpy as np

# 1. np.array()

In [ ]:
# Creating a 2-D array of 3x3 using numpy
x = np.array([[1,11,3],[4,7,6],[7,8,9]])

In [ ]:
x

array([[ 1, 11,  3],
       [ 4,  7,  6],
       [ 7,  8,  9]])

# 2. np.zeros()

In [ ]:
# Creating a 2-D zero array  of 3x3
y = np.zeros((3,3))

In [ ]:
y

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

# 3. np.ones()

In [ ]:
# Creating a 2-D array of 3x3 with all 1
z = np.ones((3,3))

In [ ]:
z

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

# 4. np.reshape()

In [ ]:
# reshaping an array from 3x3 to 9x1

t = x.copy()

In [ ]:
t

array([[ 1, 11,  3],
       [ 4,  7,  6],
       [ 7,  8,  9]])

In [ ]:
t.reshape(9,1)

array([[ 1],
       [11],
       [ 3],
       [ 4],
       [ 7],
       [ 6],
       [ 7],
       [ 8],
       [ 9]])

# 5. np.concatenate()





In [ ]:
#  use np.concatenate

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c =np.concatenate([a, b])


In [ ]:
c

array([1, 2, 3, 4, 5, 6])

# 6. np.mean()

In [ ]:
# taking mean of t
np.mean(t)

6.222222222222222

# 7. np.sum()

In [ ]:
# taking sum of t
np.sum(t)

56

# 8. np.min()

In [ ]:
# taking min of t
np.min(t)

1

# 9. np.max()

In [ ]:
# taking max of t
np.max(t)

11

# 10. np.argmax()

In [ ]:
# returning index of maximum
np.argmax(x)


1

In [ ]:
np.argmax(x,axis = 1)

array([1, 1, 2])

# 11. 	np.argmin()

In [ ]:
# returning index of minimum
np.argmin(x)


0

In [ ]:
np.argmin(x,axis = 1)

array([0, 0, 0])

# 12.	np.random.rand()

In [8]:
# creating a random array with values in range 0 to 1
r1 = np.random.rand(3,4)

In [9]:
r1

array([[0.2318537 , 0.63707914, 0.40796786, 0.95357841],
       [0.74266606, 0.0739456 , 0.58601662, 0.53822081],
       [0.53244471, 0.88781288, 0.0697255 , 0.25292916]])

# 13. 	np.random.randn()

In [10]:
# Creating a random array
r2 = np.random.randn(4,3)

In [7]:
r2

array([[-0.35798494, -0.13008043,  1.40482193],
       [ 0.87914395,  0.78375176, -0.42305281],
       [ 0.93678905, -0.33162212,  0.16113865],
       [-0.86830682, -0.22395716,  0.82208346]])




# 14. 	np.random.randint()

In [16]:
# Creating a random integers in range
rr = np.random.randint(1,8,size=(4,3))

In [17]:
rr

array([[5, 4, 1],
       [5, 2, 6],
       [1, 5, 3],
       [6, 3, 2]])

# 15. np.dot()

In [21]:
#Multiplying 2 matrix
d1 = np.dot(r1,r2)

In [22]:
d1

array([[-0.22771562, -0.61021499,  0.33346   ],
       [ 0.52512514, -0.60492807,  0.05985818],
       [-0.53201707, -0.93741722,  1.25051286]])